import type { ReactNode } from 'react';
import type { AppSnapshotMetrics } from '@/api/types';

export const APP_METRIC_FIELDS: Array<[string, (metrics: AppSnapshotMetrics) => ReactNode]> = [
  ['strengthScore', (metrics) => metrics.strengthScore ?? '—'],
  ['installsMid', (metrics) => metrics.installsMid ?? '—'],
  ['reviewsCount', (metrics) => metrics.reviewsCount ?? '—'],
  ['rating', (metrics) => metrics.rating ?? '—'],
  ['hist_pain_score', (metrics) => metrics.hist_pain_score ?? '—'],
  ['hist_share_neg', (metrics) => metrics.hist_share_neg ?? '—'],
  ['updateAgeDays', (metrics) => metrics.updateAgeDays ?? '—'],
  ['hasIAP', (metrics) => (metrics.hasIAP ? 'yes' : 'no')],
  ['iapRangeMax', (metrics) => metrics.iapRangeMax ?? '—'],
  ['iapRangeMin', (metrics) => metrics.iapRangeMin ?? '—'],
  ['iapRangeMid', (metrics) => metrics.iapRangeMid ?? '—'],
  ['iapPriceLevel', (metrics) => metrics.iapPriceLevel ?? '—'],
  ['iapMoneyScore', (metrics) => metrics.iapMoneyScore ?? '—'],
  ['iapPriceSpread', (metrics) => metrics.iapPriceSpread ?? '—'],
  ['iapRevenuePotentialProxy', (metrics) => metrics.iapRevenuePotentialProxy ?? '—'],
  ['hasAds', (metrics) => (metrics.hasAds ? 'yes' : 'no')],
  ['hist_neg_weighted_by_reviews', (metrics) => metrics.hist_neg_weighted_by_reviews ?? '—'],
  ['hist_std', (metrics) => metrics.hist_std ?? '—'],
  ['hist_entropy', (metrics) => metrics.hist_entropy ?? '—'],
  ['hist_polar_extremes_share', (metrics) => metrics.hist_polar_extremes_share ?? '—'],
  ['hist_neg_to_pos_ratio', (metrics) => metrics.hist_neg_to_pos_ratio ?? '—'],
  ['hist_avg', (metrics) => metrics.hist_avg ?? '—'],
  ['hist_trimmed_avg_2_4', (metrics) => metrics.hist_trimmed_avg_2_4 ?? '—'],
  ['hist_neg_count_est', (metrics) => metrics.hist_neg_count_est ?? '—'],
  ['ratingsCount', (metrics) => metrics.ratingsCount ?? '—'],
  ['installsMin', (metrics) => metrics.installsMin ?? '—'],
  ['installsMax', (metrics) => metrics.installsMax ?? '—'],
  ['updatedAt', (metrics) => metrics.updatedAt ?? '—'],
  ['iapRange', (metrics) => metrics.iapRange ?? '—'],
  ['price', (metrics) => metrics.price ?? '—'],
  ['isFree', (metrics) => (metrics.isFree ? 'yes' : 'no')],
  ['hist_total', (metrics) => metrics.hist_total ?? '—'],
  ['hist_share_1', (metrics) => metrics.hist_share_1 ?? '—'],
  ['hist_share_2', (metrics) => metrics.hist_share_2 ?? '—'],
  ['hist_share_3', (metrics) => metrics.hist_share_3 ?? '—'],
  ['hist_share_4', (metrics) => metrics.hist_share_4 ?? '—'],
  ['hist_share_5', (metrics) => metrics.hist_share_5 ?? '—'],
  ['hist_share_pos', (metrics) => metrics.hist_share_pos ?? '—'],
  ['hist_share_mid', (metrics) => metrics.hist_share_mid ?? '—'],
  ['hist_polar_5_minus_1', (metrics) => metrics.hist_polar_5_minus_1 ?? '—'],
  ['hist_variance', (metrics) => metrics.hist_variance ?? '—'],
  ['anomalyScore2', (metrics) => metrics.anomalyScore2 ?? '—'],
  ['anomalyScore', (metrics) => metrics.anomalyScore ?? '—'],
];

