export const CLUSTER_METRIC_FIELDS: Array<[string, string]> = [
  ['cluster_opportunity_raw', 'Opportunity'],
  ['cluster_manual_priority_raw', 'Manual priority'],
  ['cluster_demand_reviews_sum_robust', 'Reviews demand robust p75'],
  ['cluster_demand_installs_sum_mid_robust', 'Installs demand robust p75'],
  ['cluster_demand_reviews_sum_lower', 'Reviews demand lower bound'],
  ['cluster_demand_installs_sum_mid_lower', 'Installs demand lower bound'],
  ['cluster_app_pain_score_avg_weighted', 'Pain score weighted'],
  ['cluster_hist_neg_share_weighted', 'Negative share weighted'],
  ['cluster_variants_diversity_entropy_norm', 'Variants diversity entropy'],
  ['cluster_hist_polar_std_weighted', 'Polarization std weighted'],
  ['cluster_top3_share_reviews_weighted', 'Top-3 dominance'],
  ['cluster_hhi_reviews_weighted', 'HHI concentration'],
  ['cluster_top1_share_reviews_weighted', 'Top-1 dominance'],
  ['cluster_top_strength_median_reviews_weighted', 'Top strength median'],
  ['cluster_top_strength_p75_reviews_weighted', 'Top strength P75'],
  ['cluster_ghost_share_weighted', 'Ghost share weighted'],
  ['cluster_staleness_median_days_weighted', 'Staleness median days'],
  ['cluster_staleness_p75_days_weighted', 'Staleness P75 days'],
  ['cluster_iap_rate_weighted', 'IAP rate weighted'],
  ['cluster_paid_rate_weighted', 'Paid rate weighted'],
  ['cluster_ads_rate_weighted', 'Ads rate weighted'],
  ['cluster_root_iap_range_mid_avg', 'Root IAP range mid avg'],
  ['cluster_iap_money_score_weighted', 'IAP money score weighted'],
  ['cluster_iap_price_level_p75_robust', 'IAP price level P75 robust'],
  ['cluster_iap_price_level_median_weighted', 'IAP price level median weighted'],
  ['cluster_money_iap_score_raw', 'Money IAP score raw'],
  ['cluster_money_iap_score_raw_gated', 'Money IAP score raw gated'],
  ['cluster_money_factor_iap', 'Money factor IAP'],
  ['cluster_opportunity_iap_raw', 'Opportunity IAP raw'],
  ['cluster_iap_presence', 'IAP presence'],
  ['cluster_money_score_raw', 'Money score raw'],
  ['cluster_best_root_manual_priority_raw', 'Best root manual priority'],
  ['cluster_best_root_opportunity_raw', 'Best root opportunity'],
  ['cluster_best_root_demand_reviews_sum', 'Best root demand reviews'],
  ['cluster_cohesion_score', 'Cluster cohesion score'],
  ['cluster_sanity_overlap_weighted', 'Sanity overlap weighted'],
  ['cluster_demand_score_raw', 'Demand score raw'],
  ['cluster_gap_score_raw', 'Gap score raw'],
  ['cluster_monopoly_penalty_raw', 'Monopoly penalty raw'],
  ['cluster_sanity_overlap_avg', 'Sanity overlap avg'],
  ['cluster_sanity_overlap_median', 'Sanity overlap median'],
  ['cluster_sanity_overlap_p25', 'Sanity overlap p25'],
  ['cluster_sanity_overlap_p75', 'Sanity overlap p75'],
  ['cluster_demand_reviews_sum_upper', 'Reviews demand upper'],
  ['cluster_demand_installs_sum_mid_upper', 'Installs demand upper'],
  ['cluster_demand_reviews_median_weighted', 'Median reviews weighted'],
  ['cluster_demand_installs_median_mid_weighted', 'Median installs weighted'],
  ['cluster_ghost_count_sum', 'Ghost count sum'],
  ['cluster_stale_high_installs_count_sum', 'High-installs stale apps'],
  ['cluster_total_effective_apps_across_roots', 'Effective apps total'],
  ['cluster_avg_effective_apps_per_root', 'Apps per root avg'],
  ['cluster_missing_app_cards_sum', 'Missing app cards'],
  ['cluster_app_card_coverage_rate', 'App card coverage'],
  ['cluster_effective_roots_count', 'Effective roots'],
  ['cluster_root_count', 'Roots in cluster'],
];

