import type { RootMetrics } from '@/api/types';

export const ROOT_METRIC_FIELDS: Array<[string, (metrics: RootMetrics) => unknown]> = [
  ['root_opportunity_raw', (metrics) => metrics.root_opportunity_raw ?? '—'],
  ['root_manual_priority_raw', (metrics) => metrics.root_manual_priority_raw ?? '—'],
  ['root_demand_reviews_sum', (metrics) => metrics.root_demand_reviews_sum ?? '—'],
  ['root_variants_count_total', (metrics) => metrics.root_variants_count_total ?? '—'],
  ['root_variants_count_positive', (metrics) => metrics.root_variants_count_positive ?? '—'],
  ['root_variants_total_volume', (metrics) => metrics.root_variants_total_volume ?? '—'],
  ['root_variants_diversity_entropy_norm', (metrics) => metrics.root_variants_diversity_entropy_norm ?? '—'],
  ['root_variants_dominant_share', (metrics) => metrics.root_variants_dominant_share ?? '—'],
  ['root_demand_installs_sum_mid', (metrics) => metrics.root_demand_installs_sum_mid ?? '—'],
  ['root_top3_share_reviews', (metrics) => metrics.root_top3_share_reviews ?? '—'],
  ['root_hist_neg_share_weighted', (metrics) => metrics.root_hist_neg_share_weighted ?? '—'],
  ['root_iap_rate', (metrics) => metrics.root_iap_rate ?? '—'],
  ['iapRangeMid', (metrics) => metrics.iapRangeMid ?? '—'],
  ['root_iap_price_level_median', (metrics) => metrics.root_iap_price_level_median ?? '—'],
  ['root_iap_price_level_p75', (metrics) => metrics.root_iap_price_level_p75 ?? '—'],
  ['root_iap_money_score_weighted', (metrics) => metrics.root_iap_money_score_weighted ?? '—'],
  ['root_iap_revenue_potential_sum', (metrics) => metrics.root_iap_revenue_potential_sum ?? '—'],
  ['root_money_iap_score_raw', (metrics) => metrics.root_money_iap_score_raw ?? '—'],
  ['root_money_iap_score_raw_gated', (metrics) => metrics.root_money_iap_score_raw_gated ?? '—'],
  ['root_money_factor_iap', (metrics) => metrics.root_money_factor_iap ?? '—'],
  ['root_opportunity_iap_raw', (metrics) => metrics.root_opportunity_iap_raw ?? '—'],
  ['root_iap_presence', (metrics) => metrics.root_iap_presence ?? '—'],
  ['root_ghost_share', (metrics) => metrics.root_ghost_share ?? '—'],
  ['root_staleness_median_days', (metrics) => metrics.root_staleness_median_days ?? '—'],
  ['root_hist_polar_std_weighted', (metrics) => metrics.root_hist_polar_std_weighted ?? '—'],
  ['root_demand_reviews_median', (metrics) => metrics.root_demand_reviews_median ?? '—'],
  ['root_top1_share_reviews', (metrics) => metrics.root_top1_share_reviews ?? '—'],
  ['root_hhi_reviews', (metrics) => metrics.root_hhi_reviews ?? '—'],
  ['root_top_strength_median_reviews', (metrics) => metrics.root_top_strength_median_reviews ?? '—'],
  ['root_top_strength_p75_reviews', (metrics) => metrics.root_top_strength_p75_reviews ?? '—'],
  ['root_ads_rate', (metrics) => metrics.root_ads_rate ?? '—'],
  ['root_paid_rate', (metrics) => metrics.root_paid_rate ?? '—'],
  ['root_app_pain_score_avg', (metrics) => metrics.root_app_pain_score_avg ?? '—'],
  ['root_ghost_count', (metrics) => metrics.root_ghost_count ?? '—'],
  ['root_stale_high_installs_count', (metrics) => metrics.root_stale_high_installs_count ?? '—'],
  ['root_demand_score_raw', (metrics) => metrics.root_demand_score_raw ?? '—'],
  ['root_gap_score_raw', (metrics) => metrics.root_gap_score_raw ?? '—'],
  ['root_money_score_raw', (metrics) => metrics.root_money_score_raw ?? '—'],
  ['root_monopoly_penalty_raw', (metrics) => metrics.root_monopoly_penalty_raw ?? '—'],
  ['root_staleness_p75_days', (metrics) => metrics.root_staleness_p75_days ?? '—'],
  ['root_top_n', (metrics) => metrics.root_top_n ?? '—'],
  ['root_unique_apps_top_n', (metrics) => metrics.root_unique_apps_top_n ?? '—'],
  ['root_effective_apps_count', (metrics) => metrics.root_effective_apps_count ?? '—'],
  ['root_missing_app_cards_count', (metrics) => metrics.root_missing_app_cards_count ?? '—'],
];

