import type { MetricInfo } from './components/types';

export const ROOT_METRIC_INFO: MetricInfo[] = [
  {
    metric: 'root_opportunity_iap_raw',
    title: 'root_opportunity_iap_raw',
    how: 'root_demand_score_raw * root_gap_score_raw * root_money_factor_iap * (1 - root_monopoly_penalty_raw).',
    what: 'opportunity, где денежность берётся из ИАП-цен.',
    interpret:
      'высоко = спрос + боль + реальные дорогие IAP у сильных root (и не монополия) → интересный кандидат.',
  },
  {
    metric: 'root_opportunity_raw',
    title: 'root_opportunity_raw',
    how: 'log1p(root_demand_reviews_sum) * (root_gap_score_raw) * moneyFactor * (1 - clamp01(root_top3_share_reviews)), где moneyFactor = moneyFloor + (1-moneyFloor)*clamp01(root_money_score_raw)',
    what: 'интегральная “выгодность/вход” по этому root.',
    interpret: 'выше = приоритетнее. Ноль/низко = либо нет спроса, либо нет боли, либо нет денег, либо монополия.',
  },
  {
    metric: 'root_manual_priority_raw',
    title: 'root_manual_priority_raw',
    how: '(root_app_pain_score_avg) * (1 - clamp01(root_top3_share_reviews)) * log1p(root_demand_reviews_sum)',
    what: 'насколько стоит лезть в ручной анализ (читать отзывы/смотреть конкурентов).',
    interpret: 'выше = быстрее даст идеи для MVP/УТП.',
  },
  {
    metric: 'root_demand_reviews_sum',
    title: 'root_demand_reviews_sum',
    how: 'sum(reviewsCount(app)) по уникальным apps из выдачи root.',
    what: 'прокси масштаба спроса/аудитории в выдаче.',
    interpret: 'выше = рынок живее и “денежнее” (обычно).',
  },
  {
    metric: 'root_demand_installs_sum_mid',
    title: 'root_demand_installs_sum_mid',
    how: 'sum(installsMid(app)), где installsMid=(minInstalls+maxInstalls)/2.',
    what: 'прокси общего объёма установок у топа по запросу.',
    interpret: 'выше = шире рынок, но смотри монополию и качество.',
  },
  {
    metric: 'root_top3_share_reviews',
    title: 'root_top3_share_reviews',
    how: 'sum(top3 reviews)/sum(all reviews) по apps в выдаче.',
    what: 'насколько выдача “захвачена” тремя лидерами.',
    interpret: 'ближе к 1 = тяжело влезть органикой; ближе к 0.3–0.5 = место есть.',
  },
  {
    metric: 'root_hist_neg_share_weighted',
    title: 'root_hist_neg_share_weighted',
    how: 'weightedAvg(hist_share_neg(app), weight=ln(1+reviewsCount) clamp>=1), где hist_share_neg=(h1+h2)/T.',
    what: 'средняя доля негатива у сильных (по отзывам) приложений.',
    interpret: 'выше = массовая боль → шанс зайти “нормальной” версией.',
  },
  {
    metric: 'root_variants_count_total',
    title: 'root_variants_count_total',
    how: 'количество всех variants, найденных для root.',
    what: 'общий “фундамент” вариантов для анализа.',
    interpret: 'больше = больше потенциальных точек входа/запросов; низко может означать раннюю/ограниченную генерацию.',
  },
  {
    metric: 'root_variants_count_positive',
    title: 'root_variants_count_positive',
    how: 'количество variants с volume>0.',
    what: 'сколько вариантов реально генерят трафик.',
    interpret: 'высоко = широкий спрос; близко к 0 = узкая ниша.',
  },
  {
    metric: 'root_variants_total_volume',
    title: 'root_variants_total_volume',
    how: 'Σ volume по variants (только volume>0).',
    what: 'суммарный объём запросов относительно variants.',
    interpret: 'высоко = большой общий рынок; сравнивайте с root_demand_installs_sum и reviews за калибровку.',
  },
  {
    metric: 'root_variants_diversity_entropy_norm',
    title: 'root_variants_diversity_entropy_norm',
    how: 'среди variants с volume>0 считаем доли p_i = volume_i / Σvolume, H = -Σ p_i·ln(p_i), нормализуем как H / ln(n) (n==1 → 0, n==0 → null).',
    what: 'нормализованная энтропия распределения объёмов variants, диапазон 0..1.',
    interpret:
      'ближе к 0 — почти весь спрос в 1–2 запросах (жёсткая ниша), ближе к 1 — спрос распределён по long-tail и проще выбрать поднишевую идею.',
  },
  {
    metric: 'root_variants_dominant_share',
    title: 'root_variants_dominant_share',
    how: 'max(volume)/Σvolume среди variants с volume>0.',
    what: 'доля самого громкого запроса в общем объёме.',
    interpret: 'ближе к 1 — один запрос доминирует, ниша концентрирована; ближе к 0 — объём равномерно распределён.',
  },
  {
    metric: 'root_iap_rate',
    title: 'root_iap_rate',
    how: 'count(app.hasIAP)/appsCount.',
    what: 'доля приложений с IAP/подписками в выдаче.',
    interpret: 'выше = ниша вероятно платежеспособнее.',
  },
  {
    metric: 'root_iap_price_level_median',
    title: 'root_iap_price_level_median',
    how: 'median(app.iapPriceLevel) по apps с hasIAP && iapPriceLevel != null.',
    what: 'типичный уровень цен IAP в выдаче.',
    interpret: 'высокое значение = ниша со стабильными дорогими IAP, null/низкое = редкие/дешёвые покупки.',
  },
  {
    metric: 'root_iap_price_level_p75',
    title: 'root_iap_price_level_p75',
    how: 'p75(app.iapPriceLevel) по apps с hasIAP && iapPriceLevel != null.',
    what: 'высший сегмент цен (дорогие покупки/подписки).',
    interpret: 'высокий p75 = в нише регулярно встречаются дорогие IAP (возможно подписки).',
  },
  {
    metric: 'root_iap_money_score_weighted',
    title: 'root_iap_money_score_weighted',
    how: 'weightedAvg(app.iapMoneyScore, w=max(1, ln(1+reviewsCount))).',
    what: 'взвешенная денежность IAP в выдаче.',
    interpret: 'высоко = сильные запросы монетизируют дорого. Низко при высоком спросе = рынок больше про ads/free.',
  },
  {
    metric: 'root_money_iap_score_raw',
    title: 'root_money_iap_score_raw',
    how: 'clamp01(root_iap_money_score_weighted / ln(1 + IAP_PRICE_CAP)).',
    what: 'нормализованный (0..1) денежный скор IAP по root на основе цен у лидеров.',
    interpret:
      'ближе к 1 = в нише у сильных конкурентов дорогие покупки/подписки; 0 = IAP либо отсутствует, либо мал.',
  },
  {
    metric: 'root_iap_presence',
    title: 'root_iap_presence',
    how: 'pow(clamp01(root_iap_rate), IAP_RATE_EXP).',
    what: 'коэффициент “насколько IAP нормален” в root.',
    interpret:
      'низкий = IAP редкий (пару приложений); высокий = частый сигнал монетизации в выдаче.',
  },
  {
    metric: 'root_money_iap_score_raw_gated',
    title: 'root_money_iap_score_raw_gated',
    how: 'root_money_iap_score_raw * root_iap_presence.',
    what: 'денежный скор IAP (0..1) с учётом распространённости IAP.',
    interpret:
      'устраняет ложные “дорогие” сигналы, когда IAP есть только у единичных приложений.',
  },
  {
    metric: 'root_money_factor_iap',
    title: 'root_money_factor_iap',
    how: 'moneyFloor + (1 - moneyFloor) * root_money_iap_score_raw_gated.',
    what: 'moneyFactor для opportunity, основанный на IAP-ценах.',
    interpret:
      'всегда ≥ moneyFloor; ближе к 1 = ниша выглядит платежеспособной по IAP.',
  },
  {
    metric: 'root_iap_revenue_potential_sum',
    title: 'root_iap_revenue_potential_sum',
    how: 'sum(app.iapRevenuePotentialProxy) по appsForCalc.',
    what: 'суммарный прокси IAP-потенциала в выдаче.',
    interpret: 'показатель “сколько денег” потенциально в нише; удобно ранжировать, но помните — installs приближены.',
  },
  {
    metric: 'iapRangeMid',
    title: 'iapRangeMid',
    how: 'weightedAvg(app.metrics.iapRangeMid, weight=ln(1 + reviewsCount)).',
    what: 'средняя середина IAP-диапазона среди конкурентов.',
    interpret:
      'высокий iapRangeMid означает дорогие покупки/подписки, низкий — ниша больше про дешёвые допы/подписки.',
  },
  {
    metric: 'root_ghost_share',
    title: 'root_ghost_share',
    how: 'root_ghost_count / appsCount, где ghost определяется порогами (installs, age, negShare).',
    what: 'доля “призраков” (сильные по installs, старые и с негативом).',
    interpret: 'выше = хорошие шансы “обновить рынок”.',
  },
  {
    metric: 'root_staleness_median_days',
    title: 'root_staleness_median_days',
    how: 'медиана updateAgeDays(app) по apps.',
    what: 'насколько “свежий” топ по обновлениям.',
    interpret: 'выше = рынок может быть заброшен/инертен (возможность), но иногда это “устоявшийся” сегмент.',
  },
  {
    metric: 'root_hist_polar_std_weighted',
    title: 'root_hist_polar_std_weighted',
    how: 'weightedAvg(hist_std(app), weight=ln(1+reviewsCount) clamp>=1).',
    what: 'поляризация оценок у сильных приложений.',
    interpret: 'выше = нестабильность/спорный UX/монетизация → шанс зайти более “честным/стабильным”.',
  },
  {
    metric: 'root_demand_reviews_median',
    title: 'root_demand_reviews_median',
    how: 'медиана reviewsCount(app).',
    what: '“типичная” сила конкурента по отзывам.',
    interpret: 'выше = конкуренты тяжёлые; низко при высоком суммарном спросе = возможна монополия/аномалии.',
  },
  {
    metric: 'root_top1_share_reviews',
    title: 'root_top1_share_reviews',
    how: 'max(reviews)/sum(reviews).',
    what: 'степень захвата одним лидером.',
    interpret: 'ближе к 1 = “один царь”, тяжело откусить.',
  },
  {
    metric: 'root_hhi_reviews',
    title: 'root_hhi_reviews',
    how: 'sum((reviews_i/sumReviews)^2) (HHI).',
    what: 'общий индекс монополизации выдачи.',
    interpret: 'выше = более монопольно/жёстко.',
  },
  {
    metric: 'root_top_strength_median_reviews',
    title: 'root_top_strength_median_reviews',
    how: 'сейчас = root_demand_reviews_median.',
    what: 'медианная “сила топа” по отзывам.',
    interpret: 'то же, что медиана отзывов.',
  },
  {
    metric: 'root_top_strength_p75_reviews',
    title: 'root_top_strength_p75_reviews',
    how: 'p75(reviewsCount(app)).',
    what: 'сила “верхней части” топа (срез 75%).',
    interpret: 'высоко = верхушка очень сильная.',
  },
  {
    metric: 'root_ads_rate',
    title: 'root_ads_rate',
    how: 'count(app.hasAds)/appsCount.',
    what: 'насколько ниша “рекламная”.',
    interpret: 'высоко = можно делать ads-first, но ARPU часто ниже; шанс выиграть “no ads”.',
  },
  {
    metric: 'root_paid_rate',
    title: 'root_paid_rate',
    how: 'count(!app.isFree)/appsCount.',
    what: 'доля платных приложений.',
    interpret: 'если >0 — ниша допускает прямую оплату, но это редкость в Play.',
  },
  {
    metric: 'root_app_pain_score_avg',
    title: 'root_app_pain_score_avg',
    how: 'avg(appPainScore(app)), где appPainScore = hist_share_neg * ln(1+reviewsCount) (или histTotal fallback).',
    what: '“массовость боли” в среднем по выдаче.',
    interpret: 'выше = больше шансов найти конкретную боль для УТП.',
  },
  {
    metric: 'root_ghost_count',
    title: 'root_ghost_count',
    how: 'count(app where installsMid>=thr && updateAgeDays>=thr && hist_share_neg>=thr).',
    what: 'сколько “призраков” в выдаче.',
    interpret: 'больше = больше “легких целей” для замены.',
  },
  {
    metric: 'root_stale_high_installs_count',
    title: 'root_stale_high_installs_count',
    how: 'count(app where installsMid>=thr && updateAgeDays>=thr) (без условия по негативу).',
    what: 'сколько сильных и давно не обновлявшихся приложений.',
    interpret: 'высоко = рынок держится на старых решениях.',
  },
  {
    metric: 'root_demand_score_raw',
    title: 'root_demand_score_raw',
    how: 'log1p(root_demand_reviews_sum).',
    what: 'сжатый логарифмом индекс спроса.',
    interpret: 'сравнивать между root внутри одного запуска; выше = больше спрос.',
  },
  {
    metric: 'root_gap_score_raw',
    title: 'root_gap_score_raw',
    how: '(root_hist_neg_share_weighted ?? 0) + 0.5*(root_hist_polar_std_weighted ?? 0).',
    what: 'индекс “проблемности” конкурентов.',
    interpret: 'выше = больше окно для улучшения.',
  },
  {
    metric: 'root_money_score_raw',
    title: 'root_money_score_raw',
    how: '0.7*(root_iap_rate ?? 0) + 0.3*(root_paid_rate ?? 0).',
    what: 'сигнал наличия платежей в нише.',
    interpret: 'выше = больше шанс монетизации через IAP/подписку.',
  },
  {
    metric: 'root_monopoly_penalty_raw',
    title: 'root_monopoly_penalty_raw',
    how: 'clamp01(root_top3_share_reviews ?? 0).',
    what: 'штраф за захват выдачи.',
    interpret: 'ближе к 1 = хуже.',
  },
  {
    metric: 'root_staleness_p75_days',
    title: 'root_staleness_p75_days',
    how: 'p75(updateAgeDays(app)).',
    what: 'насколько “старый хвост” у выдачи.',
    interpret: 'высоко = много давно не обновлявшихся.',
  },
  {
    metric: 'root_top_n',
    title: 'root_top_n',
    how: 'len(uniqueTopApps) (все уникальные appId в снапшоте root).',
    what: 'сколько приложений было взято для расчёта (по списку выдачи).',
    interpret: 'мало = метрики менее надёжны.',
  },
  {
    metric: 'root_unique_apps_top_n',
    title: 'root_unique_apps_top_n',
    how: 'то же что root_top_n.',
    what: 'дублирующее поле “сколько уникальных”.',
    interpret: 'можно скрыть в UI, если не нужно.',
  },
  {
    metric: 'root_effective_apps_count',
    title: 'root_effective_apps_count',
    how: 'appsForCalc.length (сколько apps реально имели app-metrics).',
    what: 'сколько приложений реально участвовало в расчётах.',
    interpret: 'чем ниже относительно root_top_n, тем меньше доверия.',
  },
  {
    metric: 'root_missing_app_cards_count',
    title: 'root_missing_app_cards_count',
    how: 'max(0, root_top_n - root_effective_apps_count).',
    what: 'сколько приложений из выдачи без карточки/метрик.',
    interpret: 'высоко = данные неполные.',
  },
];


